# Generated by Django 4.1 on 2022-08-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("insertrandom", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="books",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="insertrandom.author",
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="publisher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="insertrandom.publisher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="books",
            unique_together={("book_name", "author", "book_isbn")},
        ),
    ]
